apiVersion: v1
data:
  flag: cGljb0NURntrczNjcjM3NV80MW43X3M0ZjNfMzNmZGVhMGR9Cg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"flag":"cGljb0NURntrczNjcjM3NV80MW43X3M0ZjNfMzNmZGVhMGR9Cg=="},"kind":"Secret","metadata":{"annotations":{},"name":"ctf-secret","namespace":"picoctf"},"type":"Opaque"}
  creationTimestamp: "2026-05-20T14:38:22Z"
  name: ctf-secret
  namespace: picoctf
  resourceVersion: "386"
  uid: 6fe48481-a36a-4c03-82ad-af9f64c97352
type: Opaque
